### ISSUE TITLE
Backendsprache bei Addonname nicht berücksichtigt

### ISSUE THREAD

**Issue by 191977** [FriendsOfREDAXO/global_settings#10]
![Screenshot_20190902-095921](https://user-images.githubusercontent.com/47699885/64099068-b2b4d880-cd68-11e9-9b0f-52a76a8191d9.jpg)
Kleiner Bug...

**Comment by skerbis** [comment]
Ist kein Bug, es fehlt einfach eine englische Übersetzung. Das springt REDAXO automatisch auf Deutsch um.  - PR Welcome -

**Comment by 191977** [comment]
Wie ich sehe fehlt englisch noch komplett? Mach ich mich morgen im Zug mal ran...

**Comment by skerbis** [comment]
Sehr nützlich übrigens: https://www.deepl.com/de/app/

**Comment by skerbis** [comment]
@191977 danke
