### ISSUE TITLE
Verwendung von REX_GLOBAL_VAR[my_field] in den Editoren

### ISSUE THREAD

**Issue by MC-PMOE** [FriendsOfREDAXO/global_settings#19]
Ein tolles Feature wäre, wenn man die globalen Werte via REX_GLOBAL_VAR[my_field] in den Editoren (cke5, redactor etc.) setzen könnte. 
Vllt. über eine Funktion die vom AddOn bereitgestellt wird nach dem Motto:
`rex_global_settings::replaceAll($text)`
Ähnlich der Funktionsweise des Sprog-AddOns:
`sprogdown($text, $clang_id = null)`

**Comment by skerbis** [comment]
du könntest den Outputfilter einfach noch mal anstoßen
$content = rex_extension::registerPoint(new rex_extension_point('OUTPUT_FILTER', $content));
