### ISSUE TITLE
Params von Feldern auslesen

### ISSUE THREAD

**Issue by tema-web** [FriendsOfREDAXO/global_settings#2]
Vorab: bin gerade über dieses AddOn gestolpert und muss sagen: geiler Scheiß :heart_eyes:

Was ich gerade noch vermisse:  Eine Methode zum auslesen der Standardwerte (z.B. bei Selects, Checkboxen, ...)

**Comment by skerbis** [comment]
Kannst du das bitte genauer erläutern?

**Comment by tema-web** [comment]
Klar doch, wobei ich merke, dass ich das noch nicht zu Ende gedacht habe und das die Mehtode getDefaultValue ja eigentlich genau das macht was ich wollte und ich eigentlich die params auslesen will. Werde das Issue mal umbenennen.

Mir schwebt folgendes vor: Für diverse Einstellungen baue ich in meinen Modulen definierte Einstellungsmöglichkeiten ein. Meist sind das Select-Menüs, z.B. die Container-Einstellung für Bootstrap. Da habe ich dann ein Select-Menü mit den Werten ''|container|container-fluid und definiere einen Default-Wert (passiert alles in einer Project-Klasse). Den Default-Wert kann ich jetzt einfach mit den global_settings setzen und muss nicht in die Datei. Cool wäre natürlich, wenn ich auch die Werte-Definition (die Params) auslesen könnte, um daraus das Select-Menü zusammen zu bauen. So passt das immer und muss nicht doppelt gepflegt werden.

**Comment by skerbis** [comment]
Ah. Das ist ne coole Idee.

**Comment by tema-web** [comment]
Na das mein ich doch :snowman:
Was fast mit dazu gehört: ebenfalls den Titel des Feldes mit auslesen für das Label :wink:

**Comment by skerbis** [comment]
Also was du noch brauchst ist also ein getFieldDefinition()

**Comment by tema-web** [comment]
jepp, das klingt genau nach dem, was ich mit vorstelle

**Comment by skerbis** [comment]
Machst du einen PR?

**Comment by tema-web** [comment]
Gerne, hab so etwas aber noch nie genacht … gibt’s irgendwo eine Kurzanleitung, wie ich so etwas a, besten mache?


Am 22.07.2019 um 08:58 schrieb Thomas Skerbis <notifications@github.com<mailto:notifications@github.com>>:


Machst du einen PR?

**Comment by skerbis** [comment]
Es gibt immer ein erstes mal ;-) 
Alles Wissenswerte solltest Du hier finden: https://github.com/FriendsOfREDAXO/api_docs/archive/master.zip

**Comment by tema-web** [comment]
Hm ... hab da nichts zu PRs gefunden ... vielleicht sollte ich mir das bei Gelegenheit mal anschauen. Jetzt ist aber die Zeit etwas eingeschränkt, von daher die Frage: kannst du nicht den folgenden Code-Schnipsel in die Klasse rex_global_settings mit einbauen?:
`public static function getFieldDefinition($field) {
    	$field = self::FIELD_PREFIX . self::getStrippedField($field);
	$sql = rex_sql::factory();
        $result = $sql->getArray('SELECT * FROM '. rex::getTablePrefix() . 'global_settings_field WHERE name = :name',['name'=>$field]);
        return $result[0];
	}`

**Comment by skerbis** [comment]
Sorry. Irgendwie ist der falsche Link reingerutscht. 
https://friendsofredaxo.github.io/info#ein-repo-forken-um-einen-pull-request-zu-starten

**Comment by skerbis** [comment]
Ich übernehme Deinen Code ;-)

**Comment by skerbis** [comment]
Danke @tema-web
