### ISSUE TITLE
Checkbox Darstellung

### ISSUE THREAD

**Issue by chrisrex** [FriendsOfREDAXO/global_settings#24]
Eine einzelne Checkbox wird nicht korrekt dargestellt. Bei Parameter setze ich dieses ein **1:ja** 
Der Wert "ja" wird aber nicht dargestellt. Stattdessen wird die Feldbezeichnung rechts neben die Checkbox gestellt. Die Feldbezeichnung sollte links vorne stehen und der Wert rechts von der Checkbox. Wenn ich zwei Checkboxen verwende, sieht alles gut aus 1:ja|2:nein

**Comment by eaCe** [comment]
Ich mach hier mal zu, wenn es weiterhin ein Problem ist gerne wieder öffnen
