### ISSUE TITLE
Datei im Medienpool kann nicht gelöscht werden

### ISSUE THREAD

**Issue by alexwenz** [FriendsOfREDAXO/global_settings#35]
Versionen: 
REDAXO 5.12.1
global_settings 2.6.0 
PHP 7.4.25-he.0
MySQL 8.0.26

global_settings aktiviert, bisher noch keine Felder angelegt.

Beim Versuch, eine nicht verwendete Mediendatei aus dem Medienpool zu löschen erscheint ein Ooops mit folgender Fehlermeldung:

`Error while executing statement "SELECT * FROM rex_global_settings` WHERE teambild_1.jpg IN()": SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '` WHERE teambild_1.jpg IN()' at line 1`

Fehler kommt auch bei angelegten Feldern.

**Comment by skerbis** [comment]
Ist es das? https://github.com/FriendsOfREDAXO/global_settings/pull/34/commits/5d0dbf0d9155dabf86a169fbaf4c9c5f69c10985

**Comment by alexwenz** [comment]
Wahrscheinlich. Hab ich glatt übersehen. Sorry.

**Comment by isospin** [comment]
> Ist es das? [5d0dbf0](https://github.com/FriendsOfREDAXO/global_settings/commit/5d0dbf0d9155dabf86a169fbaf4c9c5f69c10985)

ja, das sollte den fehler beheben
