### ISSUE TITLE
Nach Update von 2.5 auf 2.6 Bug beim Anlegen neuer Felder

### ISSUE THREAD

**Issue by bitshiftersgmbh** [FriendsOfREDAXO/global_settings#36]
Ich kann es aktuell gut vergleichen, weil 2 identische Systeme laufen. Auf dem einen noch die 2.5.1 und auf dem anderen aktualisiert auf die neueste Version.

Wenn ich ein neues Feld anlege (haben "text" und "media_widget" probiert), wird in der `rex_global_settings` zwar die neue Spalte ergänzt, aber der Eintrag in `rex_global_settings_field`fehlt. 

Kann jemand das Verhalten bestätigen?

**Comment by bitshiftersgmbh** [comment]
Ursache: Die Spalte "notice" wurde beim Update nicht mit angelegt, damit versacken alle `->insert()` Kommandos.

**Comment by eaCe** [comment]
@bitshiftersgmbh danke für den Hinweis, ich hatte angenommen das die install.php immer ausgeführt wird. Ein reinstall wird das Problem sicher erst mal beheben. 
Werde das die Tage fixen und noch eine update.php anlegen.

**Comment by skerbis** [comment]
@eaCe 

Setze das in die update.php und includiere dies in die install.php 

https://github.com/FriendsOfREDAXO/global_settings/blob/4926984eaaed69534285bc5d7eaa83069f537700/install.php#L3-L21

**Comment by eaCe** [comment]
https://github.com/FriendsOfREDAXO/global_settings/commit/63a6cf7581926bd342729813434b5df721e400da
