### ISSUE TITLE
Probleme mit pjax im Zusammenhang mit textarea (tinyMCEedtor)

### ISSUE THREAD

**Issue by rolandsee** [FriendsOfREDAXO/global_settings#40]
Hi,
ich denke, es gibt Probleme beim Einsatz von textarea Feldern mit dem tinyMCEeditor im Zusammenhang mit pjax:true.
Wenn ich im textarea Inhalte eingebe und speichere, dann ist im Eingabefeld des Editors der HTML Quelltext zu sehen. Erst bei einem manuellen Reload ist die gängige tinyMCE Ansicht wieder da.
Testweise habe ich in der package.yml pjax auf false gesetzt. Dann war das Verhalten und die Anzeige nach dem Speichern von Inhalten wie erwartet.
Aber eine dauerhafte Lösung wird die Änderung in der package.yml nicht sein, denn beim nächsten Update des AddOns ist diese wohl wieder futsch.

![tinymce-nach-speichernn--vor-reload](https://user-images.githubusercontent.com/4113894/154930168-359fa0a3-5342-44d5-ba25-9be1b9194e02.jpg)
![tinymce-nach-speichern--nach-reload](https://user-images.githubusercontent.com/4113894/154930175-4abaec13-0a3c-4b28-8679-295f37b93897.jpg)
![tinymce-felddefinition](https://user-images.githubusercontent.com/4113894/154930179-0ee80f42-c814-4845-9c28-cf7309c97c5b.jpg)
![global-settings-package-yml](https://user-images.githubusercontent.com/4113894/154930182-e1d5c25b-6924-48df-8bb6-978adb4a5e8a.jpg)

**Comment by skerbis** [comment]
Welcher TinyMCE ist das?

**Comment by rolandsee** [comment]
Das ist der 4er TinyMCE. Ob sich der 5er in diesem Fall anders verhält, muss ich testen.
