### ISSUE TITLE
Deinstallation oder löschen nicht möglich

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/global_settings#43]
Error thrown with message "Class "rex_global_settings" not found"

Stacktrace:
#8 Error in /homepages/44/d4295447/htdocs/redaxo/src/addons/global_settings/uninstall.php:9
#7 require in /homepages/44/d4295447/htdocs/redaxo/src/core/lib/packages/package.php:285
#6 rex_package:includeFile in /homepages/44/d4295447/htdocs/redaxo/src/core/lib/packages/manager.php:225
#5 rex_package_manager:uninstall in /homepages/44/d4295447/htdocs/redaxo/src/core/lib/packages/addons/manager.php:62
#4 rex_addon_manager:uninstall in /homepages/44/d4295447/htdocs/redaxo/src/core/lib/packages/api_package.php:34
#3 rex_api_package:execute in /homepages/44/d4295447/htdocs/redaxo/src/core/lib/api_function.php:180
#2 rex_api_function:handleCall in /homepages/44/d4295447/htdocs/redaxo/src/core/backend.php:234
#1 require in /homepages/44/d4295447/htdocs/redaxo/src/core/boot.php:143
#0 require in /homepages/44/d4295447/htdocs/redaxo/index.php:9

**Error:** Class "rex_global_settings" not found
**File:** redaxo/src/addons/global_settings/uninstall.php
**Line:** 9

<details>
<summary>Stacktrace</summary>

| Function                       | File                                            | Line     |
| ------------------------------ | ----------------------------------------------- | -------- |
| require                        | redaxo/src/core/lib/packages/package.php        | 285      |
| rex_package->includeFile       | redaxo/src/core/lib/packages/manager.php        | 225      |
| rex_package_manager->uninstall | redaxo/src/core/lib/packages/addons/manager.php | 62       |
| rex_addon_manager->uninstall   | redaxo/src/core/lib/packages/api_package.php    | 34       |
| rex_api_package->execute       | redaxo/src/core/lib/api_function.php            | 180      |
| rex_api_function::handleCall   | redaxo/src/core/backend.php                     | 234      |
| require                        | redaxo/src/core/boot.php                        | 143      |
| require                        | redaxo/index.php                                | 9        |

</details>
<details>
<summary>System report (REDAXO 5.13.2, PHP 8.0.16, MySQL 5.7.36)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.2     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.0.16     |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.36 |
| Character set | utf8mb4      |

</details>

**Comment by eaCe** [comment]
Danke @skerbis das war noch ein Überbleibsel. Interessant das es bisher nicht zu diesem Problem kam.
