### ISSUE TITLE
search-term bei Sprachwechsel im BE übernehmen

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/global_settings#45]
Wenn man in einer Sprache in der Übersichtstabelle eine Suche durchführt und und anschliessend die Sprache wechselt, sollte der Suchbegriff beibehalten werden.

Das sollte wahrscheinlich über eine Parameter-URL á la `index.php?page=sprog/wildcard/clang3&search-term=download` machbar sein, da die Suche so bereits funktioniert.

Im Grunde müsste man also nur die Sprachwechsel-Links oben anders verlinken.

**Comment by eaCe** [comment]
@danspringer falsches Repo?

**Comment by danspringer** [comment]
japp :-D
Gehört zu Sprog.
Ich close gleich hier.
