### ISSUE TITLE
Deprecation warnung

### ISSUE THREAD

**Issue by AndiLeni** [FriendsOfREDAXO/global_settings#46]
Hallo, 

ich bekomme mit php 8.1 eine deprecation warning. global_settings ist 2.8.1

`Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in redaxo\src\addons\global_settings\lib\table_expander.php on line 167`

**Comment by eaCe** [comment]
Danke für den Hinweis, werde das am Wochenende angehen.
