### ISSUE TITLE
felder, die in einem tab mit dem attribut perm="admin[]" liegen werden geleert, wenn user kein admin

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/global_settings#49]
REDAXO 	5.14.1
PHP 	8.1.7
global_settings 	2.8.2

felder mit dem attribut `perm="admin[]"` sind leer nachdem ein be-user, der kein admin ist, die einstellungen gespeichert hat

**Comment by eaCe** [comment]
@isospin das kann ich mit einem sehr einfachen Setup aktuell nicht reproduzieren. Das Textfeld wird ausgeblendet und beim speichern wird nur das geänderte Feld übernommen, das alte bleibt bestehen. 
Kannst du mir mal deine Felder geben? Sind die in Tabs, gibt es sonstige Besonderheiten?

**Comment by isospin** [comment]
es gibt tabs und ein tab hat die beschränkung `perm="admin[]"` 
die nachfolgenden felder haben die beschränkung nicht (das ist oben falsch beschrieben)

**Comment by eaCe** [comment]
Mit dem Tab kann ich es nun nachvollziehen. Danke. 
Der Kram ist ordentlich verworren, da muss ich mich noch ein mal länger mit beschäftigen.

**Comment by eaCe** [comment]
@isospin ich denke das passt nun. Es wäre super wenn du das mal testen könntest:
https://github.com/FriendsOfREDAXO/global_settings/commit/c902708c2b9307aa201d762c206dba445d16d315

**Comment by isospin** [comment]
funktioniert! vielen dank!!

**Comment by eaCe** [comment]
Super, dann werde ich die Tage einen neuen Release erstellen. Danke!
