### ISSUE TITLE
Caching REX_GLOBAL_VAR

### ISSUE THREAD

**Issue by MC-PMOE** [FriendsOfREDAXO/global_settings#5]
`REX_GLOBAL_VAR[var=my_field]`
scheint im Gegensatz zu
`rex_global_settings::getString('my_field')`
gecached zu werden, zumindest war es in meinem Fall so, dass Änderungen bei der Ausgabe mit GLOBAL VAR erst nach dem löschen des Systemcaches angezeigt wurden im Frontend.
Soll das in diesem Fall so sein? Dann wäre vermutlich ein kleiner Hinweis dazu gut.

**Comment by skerbis** [comment]
Nein, soll nicht so sein und kann ich aktuell nicht bestätigen, dass es so ist.

**Comment by skerbis** [comment]
@MC-PMOE wo hast du das VALUE im Einsatz? In einem Template oder Modul?  
Ist evtl. ein AddOn im Einsatz das ein eigenes Caching mitbringt? Z.B. Multiglossar?

**Comment by MC-PMOE** [comment]
Direkt im Template, das AddOn "Cache Warmup" ist installiert ändert aber nichts wenn ich es deaktiviere.

**Daten des Systems:**
Redaxo: 5.7.1
PHP: 7.3.2
MySQL: 5.6.43-84.3

Hab es gerade nochmal in einem anderen System probiert, selbes Problem.
Und du kannst es gar nicht reproduzieren? Ich teste mal rum ob ich irgendwelche Zusammenhänge entdecken kann...

**Comment by skerbis** [comment]
Habe es gerade in 2 Präsenzen probiert. Einmal mit PHP 7.1 und einmal mit 7.3.5

**Comment by skerbis** [comment]
@MC-PMOE bitte aktuelle GitHub-Version testen

**Comment by MC-PMOE** [comment]
Hat leider nichts verändert, aber jetzt Whoopst er bei **@** oder bei einem Bindestrich

**Comment by skerbis** [comment]
@gharlan kannst du helfen?

**Comment by gharlan** [comment]
Also ich denke, ich würde die Var so in der Art notieren (ungetestet):

```php
class rex_var_global_var extends rex_var
{
    protected function getOutput()
    {
        $var = $this->getParsedArg('var', null, true);
        if (null === $var) {
            return false;
        }

        if ($this->getArg('empty') == '1') {
            $method = 'getDefaultValue';
        } else {
            $method = 'getString';
        }

        return "rex_escape(rex_global_settings::$method($var))";
    }
}
```

Bzgl. `empty` habe ich die Logik aus der vorhandenen Var übernommen.
Was ich geändert habe:

* Für den `var`-Key habe ich `getParsedArg` statt `getArg` genommen. Zum Einen, damit man es direkt als PHP-Ausdruck bekommt (mit Anführungsstrichen drum rum), den man im PHP-Code unten direkt verwenden kann. Zum Anderen, weil so auch verschachtelte Vars möglich sind, auch wenn das hier vielleicht eher selten benötigt wird. Aber theoretisch ist dadurch sowas möglich wie `REX_GLOBAL_VAR[var="REX_PROPERTY[namespace=project key=my_global_var_key]"]`.
* Bei `getParsedArg` habe ich als dritten Parameter `true` übergeben, damit `var` der Defaultkey ist, man ihn also auch weglassen kann. Also statt `REX_GLOBAL_VAR[var=foo]` kann man nun auch `REX_GLOBAL_VAR[foo]` schreiben.
* Statt die eigentlichen Methoden von `rex_global_settings` direkt aufzurufen, liefere ich nun den PHP-Code, der den Aufruf macht. Somit landet nicht der Wert direkt, sondern der PHP-Code im Cache, und man erhält daher immer den aktuellen Wert.
* Ich habe noch `rex_escape` hinzugefügt, da müsstest du nochmal überlegen, ob das hier richtig ist. Also ob HTML als HTML rauskommen soll, oder ob die Zeichen escaped werden sollen.

**Comment by skerbis** [comment]
@gharlan Danke. Die Beschreibung ist so gut, dass wir sie so in die Doku übernehmen können. Was meinst Du? Jetzt wird mir das alles klarer. @MC-PMOE magst Du das bei Dir bitte testen?

**Comment by skerbis** [comment]
Ist im aktuellen Release gefixt. Danke @gharlan

**Comment by skerbis** [comment]
Habe rex_escape wieder rausgenommen, da HTML-Eingaben dann nicht funktionieren.
