### ISSUE TITLE
Spectrum colorpicker verbessern - alpha 

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/global_settings#50]
**Feature description / Feature Beschreibung**
Vorschlag: preferredFormat auf rgb ändern und die Option showAlpha: true ergänzen (alpha geht mit preferredFormat hex nicht)

**Comment by eaCe** [comment]
Eventuell könnte man das über eine Einstellung regeln. Da wird jeder andere Vorlieben haben.

**Comment by skerbis** [comment]
Der Color Picker wurde seit Ewigkeiten nicht mehr aktualisiert. Ich würde ihn entfernen und durch was frisches ersetzen.

**Comment by eaCe** [comment]
Das macht eventuell Dinge kaputt.

**Comment by skerbis** [comment]
was denn?

**Comment by eaCe** [comment]
Das weiß ich noch nicht :)

**Comment by eaCe** [comment]
Vielleicht: https://github.com/mdbassit/Coloris
Oder eben gleich: https://caniuse.com/input-color

**Comment by skerbis** [comment]
System finde ich gut. Aber ich glaube auf Windows-Systemen ist der eher bescheiden. Colors sieht nett aus.

**Comment by eaCe** [comment]
Da fällt mir ein @fietstouring du hattest das mit den data-Attributen getestet? https://github.com/FriendsOfREDAXO/global_settings#colorpicker

**Comment by fietstouring** [comment]
nein, nur im JS hinzugefügt.

**Comment by eaCe** [comment]
@fietstouring ich denke die Attribute werden dein Problem beheben. Teste das gerne aus.
