### ISSUE TITLE
Komplett überarbeiten

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/global_settings#53]
Der Code ist sehr in die Jahre gekommen.
Da das Addon aber sehr häufig genutzt wird, müssen die grundlegenden Funktionen erhalten bleiben

**Comment by alxndr-w** [comment]
Das Addon entstand zu Zeiten, als es noch kein rex_config_form gab und auch keine yrewrite_meta_infos bzw. yrewrite_domain_settings als Addons. 

Ich habe es in keinem neuen Projekt mehr in Verwendung, auch wenn ich damals großer Fan des Addons und der GUI war.

Von meiner Seite aus darf das Addon gerne sterben, aber man könnte es vor im Slack an `@channel` zur Diskussion stellen.

**Comment by eaCe** [comment]
Ich habe Projekte in denen auch größere Inhalte über das Addon gepflegt werden. Das sehe ich nicht in Meta, Domain und auch nicht in der REDAXO-Config. Ich meine das Addon wird schon häufig genutzt, können es aber gerne zur Diskussion stellen.

**Comment by alxndr-w** [comment]
Natürlich hat das Addon an sich auch seine Berechtigung. 

Vorteile der YForm-Domain-Geschichte:

* Nutzt vorhandenes Addon als Basis 
* Multidomainfähig
* Mehr Feldtypen und Validierungem
* ggf. Mehrsprachigkeit abbildbar

Der Vorteil von rex_config_form:
* Nutzt vorhandenen Core-Code als Basis

Da nochmal eine dritte Lösung für Zusatzinformationen für eine Website pro Sprache zu warten sollte gut überlegt sein, aber hindern möchte ich dich nicht daran.

**Comment by fietstouring** [comment]
abgesehen davon dass ich das Addon selbst extensiv nutze ist mir noch keine Lösung untergekommen mit der ich **Redakteuren** ganz einfach verschiedene **User-Settings** zur Verfügung stellen kann ohne dass diese in irgendwelchen YForm Tabellen herumfuhrwerken müssen. Die Datenbank-Umsetzung ist aber in der Tat verbesserungswürdig.

**Comment by alxndr-w** [comment]
@fietstouring hast du mal `rex_config_form` ausprobiert?

**Comment by fietstouring** [comment]
@alxndr-w nein noch nicht, dafür bräuchte ich dann qausi ein leeres Addon (wenns nur um Settings geht)?

**Comment by alxndr-w** [comment]
Ja, ein leeres Addon wie zum Beispiel das Project-Addon. Berechtigungen/Rollen kannst du dann bspw. über die package.yml definieren oder pro Eingabefeld.

**Comment by fietstouring** [comment]
@alxndr-w ok danke, das probier ich gleich mal aus. die Werte bekomme ich dann anscheinend über `rex_config::get($addon, $key);` über die package.yml kann ich ja einzelne subpages zb nur für admins sichtbar machen, wie kann ich das pro Eingabefeld setzen?

**Comment by eaCe** [comment]
Zur Abstimmung: https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1704813818026569

**Comment by eaCe** [comment]
Ich mach hier erst mal zu
