### ISSUE TITLE
Datumsfelder

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/global_settings#54]
Die Datumsfelder sehen sehr unpraktisch aus, könnte man ggf im Layout etwas anpassen. Es ist auch unklar, was der Haken danach macht…

<img width="636" alt="image" src="https://github.com/FriendsOfREDAXO/global_settings/assets/688274/01ac43f0-9a4b-49d3-bd28-24a56f1a6c52">

**Comment by skerbis** [comment]
Das Feld basiert auf eine frühere Version der metainfos und müsste wohl mal aktualisiert werden.

**Comment by eaCe** [comment]
Ich habe doch auch keine Ahnung was das macht @skerbis ich schau es mir mal an

**Comment by eaCe** [comment]
Die Checkbox deaktiviert das Datum einfach. Ich denke das hatte sicher mal einen Grund. Ich verstehe diesen aber leider nicht. Wählt man sie ab, wird die Timestamp aus der Tabelle gelöscht.

**Comment by eaCe** [comment]
Reicht es denn, wenn die Felder einfach nebeneinander erscheinen? Ich würde dann auch die Checkbox entfernen, ergibt für mich keinen Sinn.

**Comment by eaCe** [comment]
![grafik](https://github.com/FriendsOfREDAXO/global_settings/assets/2708231/2eab4211-1514-4978-9450-0d09c8207a36)

**Comment by cukabeka** [comment]
Danke, sieht super aus. Das Häkchen braucht es IMHO nicht.

**Comment by eaCe** [comment]
https://github.com/FriendsOfREDAXO/global_settings/commit/d084f113de1f62894d32280281254de2efbfadd4

**Comment by skerbis** [comment]
die checkbox war für das aktivieren und deaktivieren da. So wie in den Metas

**Comment by eaCe** [comment]
@skerbis ist das wichtig? Ich bin da nicht so tief drin, wenn das gebraucht wird, baue ich es wieder ein

**Comment by skerbis** [comment]
ja könnte wichtig sein. Die checkbox aktiviert z.B. einen Timer und nur so würde man ihn beachten können.

**Comment by eaCe** [comment]
Dann vielleicht so 
![grafik](https://github.com/FriendsOfREDAXO/global_settings/assets/2708231/ac696ee5-214c-40dd-bf66-c90bdffce9d5)

**Comment by skerbis** [comment]
inaktiv ausgeblendet? bzw ausgegraut?

**Comment by skerbis** [comment]
Sieht in den Metas so aus:

inaktiv 
<img width="366" alt="Bildschirmfoto 2024-06-10 um 21 24 55" src="https://github.com/FriendsOfREDAXO/global_settings/assets/791247/b2116dc5-ea5a-49d4-a30a-a6ea0c84782a">
aktiv
<img width="357" alt="Bildschirmfoto 2024-06-10 um 21 25 20" src="https://github.com/FriendsOfREDAXO/global_settings/assets/791247/935ec2cd-8a0f-4f5e-9fbf-ee9ae6f33958">

**Comment by alxndr-w** [comment]
Mit einem HTML5-Datumsfeld wäre das eigentlich erledigt - das kann man auch leer lassen, also "löschen". Warum so kompliziert und wieder mit den Usability-Nachteilen, ungültige Datumsangaben ausfüllen zu könenn? (31.02.2025 z.B.)

**Comment by skerbis** [comment]
Zur Wahrung der Kompatibilität zum Metainfo Addon

**Comment by alxndr-w** [comment]
@skerbis wozu Kompatibilität mit dem Metainfos-Addon?

**Comment by skerbis** [comment]
Und dem Addon selbst. Hier geht es nur um „Kosmetik“. Bei einem refactor könnte man drüber nachdenken
